<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Laptop" failures="2" tests="4" name="Test" time="9.034" errors="0" timestamp="2025-04-25T02:17:15 IST">
  <testcase classname="api.test.UserTest" name="testPostUser" time="3.307"/>
  <testcase classname="api.test.UserTest" name="testGetUser" time="1.327"/>
  <testcase classname="api.test.UserTest" name="testUpdateByName" time="2.762">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTest.testUpdateByName(UserTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateByName -->
  <testcase classname="api.test.UserTest" name="testDeleteUserByName" time="1.085">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTest.testDeleteUserByName(UserTest.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- Test -->
